# Runs a Play 2 application, built using deploy.yaml
# Run with: run -vv launch
---
- hosts: ec2Instance
  vars:
  - java_opts: $ENV(JAVA_OPTS)

  tasks:
  # - name: Kill all old Java processes (includes Play) to free ports and memory
  #   command: killall java -q
  #   ignore_errors: yes

  # - name: Remove old PID file if it exists
  #   action: file path=$pid_file state=absent

  # - name: Remove old $home/nohup.out file if it exists
  #   action: file path=$home/nohup.out state=absent

   # Help on Play app options: ${home}/$project/bin/$ENV(ANSIBLE_PLAY_APP_NAME)-h
   # See http://www.playframework.com/documentation/2.2.1/ProductionConfiguration
   - name: Launch project
     service: name=play state=restarted

   #- name: tail
   #  action: shell tail -f $home/nohup.out
